services:
  file-server:
    image: nginx:${NGINX_IMAGE_VERSION}
    container_name: file-server
    volumes:
      - type: volume
        source: templates
        target: /etc/nginx/templates
    ports:
      - ${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}
    configs:
      - source: default-off
        target: /docker-entrypoint.d/40-disable-nginx-default-conf.sh
        uid: 'root'
        gid: 'root'
        mode: 0550
      - source: file-server-index
        target: /html/index.html
        uid: '0'
        gid: '0'
        mode: 0550
      - source: file-server-301
        target: /html/50x.html
        uid: '0'
        gid: '0'
        mode: 0550
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

volumes:
  templates:


configs:
  default-off:
    file: ./scripts/40-disable-nginx-default-conf.sh
  file-server-index:
    file: ./html/file-serverindex.html
  file-server-301:
    file: ./html/file-server50x.html