version: '3.8'

services:
  file-server:
    image: nginx:1.25.1
    container_name: file-server
    volumes:
      - type: volume
        source: templates
        target: /etc/nginx/templates
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
      - target: 8443
        published: 8443
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: udp
        mode: ingress
      - target: 3478
        published: 3478
        protocol: tcp
        mode: ingress
      - target: 3478
        published: 3478
        protocol: udp
        mode: ingress
    configs:
      - source: file-server-conf
        target: /etc/nginx/conf.d/file-server.conf
        uid: '0'
        gid: '0'
        mode: 0550
      - source: default-off
        target: /docker-entrypoint.d/40-disable-nginx-default-conf.sh
        uid: '0'
        gid: '0'
        mode: 0550
      - source: file-server-index
        target: /html/index.html
        uid: '0'
        gid: '0'
        mode: 0554
      - source: file-server-301
        target: /html/50x.html
        uid: '0'
        gid: '0'
        mode: 0555
    environment:
      - NGINX_HOST=foobar.com

volumes:
  templates:


configs:
  file-server-conf:
    file: ./conf.d/file-server.conf
  default-off:
    file: ./scripts/40-disable-nginx-default-conf.sh
  file-server-index:
    file: ./html/file-server-index.html
  file-server-301:
    file: ./html/file-server-50x.html