services:
  dns-server:
    image: nginx:1.25.1
    container_name: adguard
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: ingress
      - target: 53
        published: 53
        protocol: udp
        mode: ingress
      - target: 67
        published: 67
        protocol: udp
        mode: ingress
      - target: 1068
        published: 68
        protocol: udp
        mode: ingress
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: udp
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
      - target: 853
        published: 853
        protocol: tcp
        mode: ingress
      - target: 853
        published: 853
        protocol: udp
        mode: ingress
      - target: 784
        published: 784
        protocol: udp
        mode: ingress
      - target: 8853
        published: 8853
        protocol: udp
        mode: ingress
      - target: 5443
        published: 5443
        protocol: tcp
        mode: ingress
      - target: 5443
        published: 5443
        protocol: udp
        mode: ingress
    volumes:
      - type: volume
        source: work-dir
        target: /opt/adguardhome/work
      - type: volume
        source: conf-dir
        target: /opt/adguardhome/conf
    configs:
      - source: dns-server-conf
        target: /etc/nginx/conf.d/dns-server.conf
        uid: '0'
        gid: '0'
        mode: 0550
      - source: default-off
        target: /docker-entrypoint.d/40-disable-nginx-default-conf.sh
        uid: '0'
        gid: '0'
        mode: 0550
      - source: dns-server-index
        target: /html/index.html
        uid: '0'
        gid: '0'
        mode: 0554
      - source: dns-server-301
        target: /html/50x.html
        uid: '0'
        gid: '0'
        mode: 0554
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

volumes:
  work-dir:
  conf-dir:

configs:
  dns-server-conf:
    file: ./conf.d/dns-server.conf
  default-off:
    file: ./entrypoint.d/40-disable-nginx-default-conf.sh
  dns-server-index:
    file: ./html/dns-server-index.html
  dns-server-301:
    file: ./html/dns-server-50x.html